Update PR workflow to use versions in name

diff --git a/.github/workflows/kubectl-create-bump-pr.yml b/.github/workflows/kubectl-create-bump-pr.yml
--- a/.github/workflows/kubectl-create-bump-pr.yml
+++ b/.github/workflows/kubectl-create-bump-pr.yml
@@ -59,10 +59,26 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Check for changes
+        id: changes_check
         if: ${{ env.is_supported == 'true' }}
         run: |
-          rm -f .github/scripts/bump-kubectl-patch-versions
+          rm -f .github/scripts/bump-kubectl-patch-versions || true
           git restore --staged --worktree .github/scripts/bump-kubectl-patch-versions || true
+
+          # Read log for PR title and clean up log file
+          LOG_FILE="kubectl-version.txt.log"
+          if [[ -f "$LOG_FILE" ]]; then
+            # Check if the log file exists and is not empty
+            if [[ -s "$LOG_FILE" ]]; then
+              LOG_TITLE=$(cat "$LOG_FILE" | awk '{printf "%s%s", (NR==1?"":", "), $0} END{print ""}')
+              echo "Log file content found, created title:"
+              echo "$LOG_TITLE"
+              echo "pr_title_versions=$LOG_TITLE" >> GITHUB_OUTPUT
+            fi
+          
+            echo "Removing log file: $LOG_FILE"
+            rm "$LOG_FILE"
+          fi
 
           if git diff --quiet; then
             echo "No changes detected."
@@ -108,7 +124,7 @@ jobs:
         if: ${{ env.changes_exist == 'true' }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          PR_TITLE: "Automated `kubectl` update for `${{ inputs.target_branch }}`"
+          PR_TITLE: "[${{ inputs.target_branch }}] Automated `kubectl` updates: `${{ steps.changes_check.outputs.pr_title_versions }}`"
         run: |
           EXISTING_PR=$(gh pr list --limit 100 --json title,url \
             | jq --arg t "${PR_TITLE}" -r '.[] | select(.title==$t) | .url')
